name: GreyScript PR Check

on:
  pull_request:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - name: Install greybel
      run: npm install -g greybel-js@latest
    - name: Test
      run: greybel-execute ./test/index.src
    - name: Build
      run: greybel ./src/json.src -i